name: Code Task

on:
  schedule:
    - cron: '*/2 * * * 1-5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shell script
        run: |
          chmod +x omni_stand_up.sh
          ./omni_stand_up.sh
