name: Update Current Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read current_index.txt
        id: read-index
        run: |
          current_index=$(cat current_index.txt)
          echo "Current index is: $current_index"
          echo "::set-output name=index::$current_index"

      - name: Modify index
        run: |
          names=("陈晗" "刘入菲" "刘文宾" "陶星蒙" "肖亭" "岳潇逸" "喻唅" "祝赫" "许俊")
          current_index=$(( $(echo "${{ steps.read-index.outputs.index }}") + 1 ) % ${#names[@]}))
          echo "Modified index is: $current_index"
          echo $current_index > current_index.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "15327163498@163.com"
          git config --local user.name "GitHub Action"
          git add current_index.txt
          git commit -m "Update current_index.txt"
          git push https://$GH_PAT@github.com/VincentXXTT/StandUp.git HEAD:main


